/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface YearData {
  year: string;
  students: number;
  facultyCount: number;
  phdCount: number;
  mastersCount: number;
  professors: number;
  associateProfessors: number;
  assistantProfessors: number;
  retentionScore: string;
  experienceA: number;
  experienceB: number;
  experienceC: number;
  experienceD: number;
}

export interface FacultyEntry {
  sn: number;
  name: string;
  pan: string;
  degree: string;
  university: string;
  specialization: string;
  joiningDate: string;
  experience: number;
  joiningDesignation: string;
  presentDesignation: string;
  nature: string;
  currentlyAssociated: boolean;
  dateDesignatedProf?: string;
  dateOfLeaving?: string;
}

export const NBA_DATA: YearData[] = [
  {
    year: "2025-26 (CAY)",
    students: 720,
    facultyCount: 36,
    phdCount: 10,
    mastersCount: 26,
    professors: 4,
    associateProfessors: 8,
    assistantProfessors: 24,
    retentionScore: "8.00",
    experienceA: 15,
    experienceB: 12,
    experienceC: 6,
    experienceD: 3
  },
  {
    year: "2024-25 (CAYm1)",
    students: 700,
    facultyCount: 35,
    phdCount: 9,
    mastersCount: 26,
    professors: 4,
    associateProfessors: 7,
    assistantProfessors: 24,
    retentionScore: "8.00",
    experienceA: 14,
    experienceB: 11,
    experienceC: 7,
    experienceD: 3
  },
  {
    year: "2023-24 (CAYm2)",
    students: 680,
    facultyCount: 34,
    phdCount: 8,
    mastersCount: 26,
    professors: 3,
    associateProfessors: 7,
    assistantProfessors: 24,
    retentionScore: "8.00",
    experienceA: 13,
    experienceB: 11,
    experienceC: 7,
    experienceD: 3
  }
];

export const INITIAL_FACULTY: FacultyEntry[] = [
  {
    sn: 1,
    name: "Dr. John Doe",
    pan: "ABCDE1234F",
    degree: "Ph.D",
    university: "Anna University",
    specialization: "CSE",
    joiningDate: "2018-06-15",
    experience: 8.5,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 2,
    name: "Dr. Jane Smith",
    pan: "BCDEF2345G",
    degree: "Ph.D",
    university: "VTU",
    specialization: "Software Engineering",
    joiningDate: "2019-01-10",
    experience: 7.5,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 3,
    name: "Dr. Alan Turing",
    pan: "CDEFG3456H",
    degree: "Ph.D",
    university: "IISc Bangalore",
    specialization: "Algorithms",
    joiningDate: "2020-07-22",
    experience: 6.0,
    joiningDesignation: "Associate Professor",
    presentDesignation: "Associate Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 4,
    name: "Dr. Grace Hopper",
    pan: "DEFGH4567I",
    degree: "Ph.D",
    university: "MIT",
    specialization: "Compilers",
    joiningDate: "2017-08-01",
    experience: 9.0,
    joiningDesignation: "Associate Professor",
    presentDesignation: "Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 5,
    name: "Dr. Ada Lovelace",
    pan: "EFGHI5678J",
    degree: "Ph.D",
    university: "Cambridge",
    specialization: "Theory of Computation",
    joiningDate: "2021-03-12",
    experience: 5.2,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Associate Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 6,
    name: "Dr. Richard Feynman",
    pan: "FGHIJ6789K",
    degree: "Ph.D",
    university: "Princeton",
    specialization: "Quantum Computing",
    joiningDate: "2019-11-05",
    experience: 6.8,
    joiningDesignation: "Associate Professor",
    presentDesignation: "Associate Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 7,
    name: "Dr. Claude Shannon",
    pan: "GHIJK7890L",
    degree: "Ph.D",
    university: "Michigan",
    specialization: "Information Theory",
    joiningDate: "2018-05-18",
    experience: 8.0,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Associate Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 8,
    name: "Dr. Barbara Liskov",
    pan: "HIJKL8901M",
    degree: "Ph.D",
    university: "Stanford",
    specialization: "Distributed Systems",
    joiningDate: "2020-02-14",
    experience: 6.2,
    joiningDesignation: "Associate Professor",
    presentDesignation: "Associate Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 9,
    name: "Dr. Tim Berners-Lee",
    pan: "IJKLM9012N",
    degree: "Ph.D",
    university: "Oxford",
    specialization: "Web Technologies",
    joiningDate: "2021-09-01",
    experience: 4.8,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Associate Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 10,
    name: "Dr. Donald Knuth",
    pan: "JKLMN0123O",
    degree: "Ph.D",
    university: "Caltech",
    specialization: "Analysis of Algorithms",
    joiningDate: "2016-01-15",
    experience: 10.5,
    joiningDesignation: "Professor",
    presentDesignation: "Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 11,
    name: "Alice Cooper",
    pan: "KLMNO1234P",
    degree: "M.Tech",
    university: "VTU",
    specialization: "Computer Networks",
    joiningDate: "2022-07-01",
    experience: 3.8,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 12,
    name: "Bob Dylan",
    pan: "LMNOP2345Q",
    degree: "M.Tech",
    university: "Anna University",
    specialization: "Cloud Computing",
    joiningDate: "2023-01-15",
    experience: 3.2,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 13,
    name: "Charlie Brown",
    pan: "MNOPQ3456R",
    degree: "M.Tech",
    university: "JNTU",
    specialization: "Cyber Security",
    joiningDate: "2021-06-20",
    experience: 4.5,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 14,
    name: "David Gilmour",
    pan: "NOPQR4567S",
    degree: "M.Tech",
    university: "Manipal University",
    specialization: "Data Science",
    joiningDate: "2022-02-10",
    experience: 4.0,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 15,
    name: "Emily Dickinson",
    pan: "OPQRS5678T",
    degree: "M.Tech",
    university: "Amrita University",
    specialization: "Information Security",
    joiningDate: "2023-08-01",
    experience: 2.5,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 16,
    name: "Frank Zappa",
    pan: "PQRST6789U",
    degree: "M.Tech",
    university: "VTU",
    specialization: "Embedded Systems",
    joiningDate: "2020-10-15",
    experience: 5.5,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 17,
    name: "George Harrison",
    pan: "QRSTU7890V",
    degree: "M.Tech",
    university: "NITK",
    specialization: "Database Systems",
    joiningDate: "2021-03-01",
    experience: 5.0,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 18,
    name: "Helen Keller",
    pan: "RSTUV8901W",
    degree: "M.Tech",
    university: "BMSCE",
    specialization: "Internet of Things",
    joiningDate: "2022-11-20",
    experience: 3.5,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 19,
    name: "Isaac Newton",
    pan: "STUVW9012X",
    degree: "M.Tech",
    university: "MSRIT",
    specialization: "Machine Learning",
    joiningDate: "2023-05-15",
    experience: 3.0,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 20,
    name: "John Lennon",
    pan: "TUVWX0123Y",
    degree: "M.Tech",
    university: "PESU",
    specialization: "Mobile Programming",
    joiningDate: "2024-01-10",
    experience: 2.2,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 21,
    name: "Karen Carpenter",
    pan: "UVWXY1234Z",
    degree: "M.Tech",
    university: "VTU",
    specialization: "Natural Language Processing",
    joiningDate: "2022-09-01",
    experience: 3.7,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 22,
    name: "Louis Armstrong",
    pan: "VWXYZ2345A",
    degree: "M.Tech",
    university: "RVCE",
    specialization: "Web Engineering",
    joiningDate: "2023-03-15",
    experience: 3.1,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 23,
    name: "Michael Jackson",
    pan: "WXYZA3456B",
    degree: "M.Tech",
    university: "JNTU",
    specialization: "Software Testing",
    joiningDate: "2021-12-01",
    experience: 4.3,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 24,
    name: "Nina Simone",
    pan: "XYZAB4567C",
    degree: "M.Tech",
    university: "Anna University",
    specialization: "Compiler Design",
    joiningDate: "2022-06-15",
    experience: 3.9,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 25,
    name: "Oscar Wilde",
    pan: "YZABC5678D",
    degree: "M.Tech",
    university: "VTU",
    specialization: "AI Ethics",
    joiningDate: "2023-10-01",
    experience: 2.3,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 26,
    name: "Paul McCartney",
    pan: "ZABCD6789E",
    degree: "M.Tech",
    university: "Manipal",
    specialization: "Cryptography",
    joiningDate: "2020-05-11",
    experience: 5.7,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 27,
    name: "Queen Elizabeth",
    pan: "ABCDE7890F",
    degree: "M.Tech",
    university: "Oxford",
    specialization: "Formal Methods",
    joiningDate: "2019-09-01",
    experience: 6.4,
    joiningDesignation: "Associate Professor",
    presentDesignation: "Associate Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 28,
    name: "Robert Plant",
    pan: "BCDEF8901G",
    degree: "M.Tech",
    university: "VTU",
    specialization: "Parallel Computing",
    joiningDate: "2021-02-18",
    experience: 5.1,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 29,
    name: "Steve Jobs",
    pan: "CDEFG9012H",
    degree: "M.Tech",
    university: "Stanford",
    specialization: "UI/UX Design",
    joiningDate: "2022-01-20",
    experience: 4.2,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Contract",
    currentlyAssociated: true,
  },
  {
    sn: 30,
    name: "Uma Thurman",
    pan: "DEFGH0123I",
    degree: "M.Tech",
    university: "JNTU",
    specialization: "Multimedia Systems",
    joiningDate: "2023-07-22",
    experience: 2.8,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 31,
    name: "Victor Hugo",
    pan: "EFGHI1234J",
    degree: "M.Tech",
    university: "Sorbonne",
    specialization: "Computational Linguistics",
    joiningDate: "2021-11-15",
    experience: 4.6,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 32,
    name: "Walt Disney",
    pan: "FGHIJ2345K",
    degree: "M.Tech",
    university: "CalArts",
    specialization: "Computer Graphics",
    joiningDate: "2022-05-12",
    experience: 3.9,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 33,
    name: "Xavier Dolan",
    pan: "GHIJK3456L",
    degree: "M.Tech",
    university: "Montreal",
    specialization: "Video Analytics",
    joiningDate: "2024-03-01",
    experience: 2.0,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 34,
    name: "Yoko Ono",
    pan: "HIJKL4567M",
    degree: "M.Tech",
    university: "Tokyo",
    specialization: "Creative Computing",
    joiningDate: "2020-04-01",
    experience: 5.9,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Regular",
    currentlyAssociated: true,
  },
  {
    sn: 35,
    name: "Zinedine Zidane",
    pan: "IJKLM5678N",
    degree: "M.Tech",
    university: "Marseille",
    specialization: "Graph Algorithms",
    joiningDate: "2022-12-01",
    experience: 3.3,
    joiningDesignation: "Assistant Professor",
    presentDesignation: "Assistant Professor",
    nature: "Contract",
    currentlyAssociated: true,
  },
  {
    sn: 36,
    name: "Dr. Albert Einstein",
    pan: "JKLMN6789O",
    degree: "Ph.D",
    university: "Zurich",
    specialization: "Theoretical Informatics",
    joiningDate: "2015-09-01",
    experience: 11.2,
    joiningDesignation: "Professor",
    presentDesignation: "Professor",
    nature: "Regular",
    currentlyAssociated: true,
  }
];
